### ISSUE TITLE
La barre de progression devient responsive centré et ne cree pas de scroll barre

### ISSUE THREAD

**Issue by Mat95rix7** [Unitystation-fork/Unitystation-MillstoneSteam#129]
aménagement du code de la barre de progression ProgressBar qui crée des scroll barre et dépasse l'écran d'affichage. elle devient dynamique et reste toujours centre avec la liste des taches et responsive avec tous les dimensions d'ecrans

**Comment by Mat95rix7** [comment]
![Capture d'écran 2024-03-27 101427](https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/assets/150734899/acd92a65-1c64-4e1d-8d76-fffae8a5c3c9)

Capture d'écran de la barre de progression

**Comment by Fr-Dae** [comment]
a vérifier comment le site rend sur edge et safari, sur firefox nous n'aviosn pas ce soucis

**Comment by Mat95rix7** [comment]
la largeur des composants de la barre de progression était fixe et si on a plus de taches, c'est obligé que ça déborde. Dès coup je l'ai rendu variable dépend des nombre de taches comme ça il reste toujours dans la page.
