### ISSUE TITLE
edit readme .md avec reference relative

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-MillstoneSteam#21]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by mortifia** [comment]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links
