### ISSUE TITLE
millestone - Api nodejs discord-connect

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-MillstoneSteam#3]

**Comment by Fr-Dae** [comment]
https://fusebit.io/blog/discord-oauth:-how-to-add-the-discord-api-to-a-node.js-app/?utm_source=www.google.com&utm_medium=referral&utm_campaign=none

**Comment by Clemy-beep** [comment]
Remplacé par ticket #11
