### ISSUE TITLE
Afficher le formulaire de modification uniquement pour la tâche active

### ISSUE THREAD

**Issue by Clemy-beep** [Unitystation-fork/Unitystation-MillstoneSteam#31]
Afficher le formulaire de modification uniquement pour la tâche active

**Comment by Clemy-beep** [comment]
@Fr-Dae tu préfères pouvoir modifier plusieurs tâches d'un coup comme c'est le cas actuellement :
![image](https://user-images.githubusercontent.com/71656865/206226881-fea7e6ef-192a-48f1-84ef-01da4f236366.png)
Ou bien n'avoir le formulaire que pour la tâche active (celle pour laquelle tu as cliqué sur le stylo) et les autres restent cachés ?

**Comment by Fr-Dae** [comment]
modifier les fiche une a une me suffi

**Comment by Mat95rix7** [comment]
maintenant on cliquant sur la tache qu'on veux modifier on aura qu'un seul formulaire de modification celle qu'on a choisit.

**Comment by Mat95rix7** [comment]
![Capture d'écran 2024-04-26 105056](https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/assets/150734899/7a54a656-24e2-4382-ba5f-8c41e69a619d)
