### ISSUE TITLE
check si oublie de recorder le merge a une issue

### ISSUE THREAD

**Issue by mortifia** [Unitystation-fork/Unitystation-MillstoneSteam#34]
copier puis mettre a jour le message pour savoir si check

- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/26 @Clemy-beep
- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/20 @Clemy-beep
- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/19 @Clemy-beep
- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/8 @Fr-Dae 
- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/7 @Clemy-beep @Fr-Dae 
- [ ] https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/pull/1 @Fr-Dae

**Comment by Clemy-beep** [comment]
#19 rattaché correctement au ticket #17 
Il y aurait dû y avoir un ticket pour le #20, je ferai plus attention les prochaines fois
Le merge #26 contient trop de commits différents pour être rattaché à un ticket (le stagiaire est pas parti de la bonne branche pour créer celle visant à résoudre le ticket #21, résolu avec merge #25)
