### ISSUE TITLE
Liste des tâches + leur description

### ISSUE THREAD

**Issue by Clemy-beep** [Unitystation-fork/Unitystation-MillstoneSteam#35]
Merci de fournir dans les commentaires de ce ticket une liste des tâches qui devront être affichées sur la page ainsi que, pour chacune, sa description (lien et/ou texte) et si cette dernière est visible pour tous ou doit être vue uniquement lorsqu'on est logué.

**Comment by Fr-Dae** [comment]
- 📄Pitch d'accoche, Pitch Minute :langage_web:👀 
- 📄Press-kit :langage_web:
- :discord: Rassembler une base de streamer et joueurs en une liste propre avec Job préférences.
- :discord: Canaux vocaux discord par département/zone
- 📄  Préparé une liste de règles et instruction streamer/viewer :langage_web:
- :OBS: Scene streamer avec tuto :langage_web:
- :server: Configuré un serveur local
- :langage_web: Traduire documentation (ajout de loi) :langage_web:
- ❓ Niveau Tutoriel Solo
- ❓ Tutoriel Français, Anglais, Allemand, Russe

- :discord: Annonces Invitation joueurs
- 📆 Doodle des participant :langage_web:
- Lien Multi stream 👀 
- :twitch~1: Stream Entrainement "security" 
- :discord: De-Briefing
- 🎙️ Voice Proximity Chat

- :discord: add Rôles streamer unitystation
- :discord: add Section FR Unitystation
- :twitch~1: Stream collaboratif

**Comment by Clemy-beep** [comment]
Toutes les tâches en haut de la liste, avant le "à faire" sont donc déjà réalisées ? 
Et j'aurais besoin des descriptions aussi, ici ou sur Discord si tu préfères pour la confidentialité des liens privés

**Comment by Fr-Dae** [comment]
je vais faire cela
