### ISSUE TITLE
Fournir le contenu du footer

### ISSUE THREAD

**Issue by Clemy-beep** [Unitystation-fork/Unitystation-MillstoneSteam#68]
@Fr-Dae  Il faut que tu me dises ce que tu veux voir apparaître dans le footer qui pour l'instant est vide (souvent on trouve les infos de contact, les liens vers les réseaux sociaux, les liens utiles, etc)

**Comment by Fr-Dae** [comment]
- lien vers le code sources
- lien vers unitystation
- contact mail + http://site.unionrolistes.fr/

si tu as d'autre idée je prend
